DEF_ERR(NO_ERROR, "no error occurred")
DEF_ERR(INVALID_CMD_NAME, "no such command was found")
DEF_ERR(TOO_MANY_ARGS, "too many arguments for this command")
DEF_ERR(INVALID_ARG, "unknown argument for this command")
DEF_ERR(TOO_FEW_ARGS, "too few arguments")