#ifndef CPU_CONSTANSTS_H
#define CPU_CONSTANSTS_H


const int FLOATING_POINT_COEFFICIENT = 100;

const size_t NUMBER_OF_CMD_BITS = 5;

const uint8_t CMD_IMMEDIATE_BIT = 0b001'00000;
const uint8_t CMD_REGISTER_BIT  = 0b010'00000;
const uint8_t CMD_MEMORY_BIT    = 0b100'00000;
const uint8_t CMD_COMMAND_BITS  = 0b000'11111;

// DSL constants.
#define SGNTR_IMM CMD_IMMEDIATE_BIT
#define SGNTR_RAM CMD_MEMORY_BIT
#define SGNTR_REG CMD_REGISTER_BIT


#endif